:concurrency: 3 # how many workers working at once
:timeout: 60
:verbose: true # saying that we want log the error
:queues:
  # defining Queue priority:
  # https://github.com/mperham/sidekiq/wiki/Advanced-Options
  # https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
